= Membuat Blog Menggunakan NextJS dan MDX [4-Dynamic Content]
:author: Excel
:create_date: 2022-11-27T21:27:13
:tagline: Membuat Blog Dengan Konten Dinamis Tanpa Content Management System (CMS)
:description: Membuat konten blog menjadi dinamis tanpa menggunakan CMS
:tag: tutorial,js,indonesia

== Dynamic Content

Tentu setiap kali kita membuat _post_ baru, maka kita ingin _post_ tersebut tampil secara otomatis setelah kita mem-_publish_-nya. Disini kita akan mengubah blog kita menjadi dinamis sehingga tidak perlu lagi melakukan konfigurasi secara manual setiap kali membuat _file Markdown_ baru.

=== getStaticProps

Pada ReactJS, cara untuk membuat input dinamis yaitu dengan memanfaatkan `props`. Masalahnya, darimana kita bisa mendapatkan input untuk `props` itu sendiri? Disini kita tidak mengambil data dari _server_ melainkan dari _file system_. Ini berarti kita perlu mendeteksi isi dari sebuah direktori tempat kita menyimpan konten.

Mungkin bila sudah biasa bermain dengan NodeJS pasti solusinya dengan menggunakan modul https://nodejs.org/api/fs.html#fs_file_system[fs]. Namun, modul `fs` tidak bisa kita gunakan di _Functional Component_. Kenapa?

Coba kita tambahkan pada *index.tsx*

[source,tsx]
----
....
import fs from "fs";

const Index: React.FC = () => {
  let directory :string[] = fs.readdirSync("posts")

  return(
  <>
    <Navbar />
  ....

----

Nantinya akan muncul _error_ seperti berikut:

[source,console]
----
Module not found: Can't resolve 'fs'

----

Ini terjadi karena _Functional Component_ di _render_ oleh _client_ menggunakan _browser,_ sedangkan _Javascript_ yang berjalan di _browser_ berbeda dengan NodeJS. NodeJS sendiri hanya bisa dijalankan di _server_ dan bila ingin mengakses direktori _file_ di _browser_ maka perlu menggunakan https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API[Browser API].

Lalu bagaimana caranya supaya kita bisa menggunakan modul `fs`? Jawabannya pasti kita harus menjalankan kodenya di _server_. Pertanyaan selanjutnya, dimana kita meletakkan kodenya supaya bisa dijalankan di _server_ ?

Disinilah kita membutuhkan `getStaticProps`. Pada https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation[dokumentasi] NextJS, `getStaticProps` merupakan fungsi untuk menjalankan _script_ di _server_ ketika melakukan _pre-rendering_ dan biasa digunakan untuk mengambil data, kemudian di _passing_ sebagai `props` ke _Functional Component._

. Buka _file_ *index.tsx* kemudian tambahkan baris berikut:
[source,tsx]
----
import { GetStaticProps } from "next";

----

. Kemudian tambahkan fungsi berikut
[source,tsx]
----
export const getStaticProps: GetStaticProps = async () => {
  const filename: string[] = fs.readdirSync("posts");
  console.log(filename);
};

----

Isi keseluruhan _file_ *index.tsx* akan seperti ini

[source,tsx]
----
import * as React from "react";
import { Navbar, Featured, Grid, Card } from "@/.";
import { GetStaticProps } from "next";
import { meta } from "posts/post-1.mdx";
import fs from "fs";

const Index: React.FC = () => (
  <>
    <Navbar />
    <main>
      <section id="featured-post">
        <Featured
          title={meta.title}
          description={meta.description}
          cover={meta.cover}
          path={`blog/${meta.uid}`}
        />
      </section>
      <section id="latest-post">
        <Grid col="320px 320px 320px" row="auto" gap="30px" justify="center">
          <Card
            title="LET'S GO SNOWBOARDING"
            subtitle="Snowboarding is a good activity y'know!"
            cover="https://images.unsplash.com/photo-1580238053771-c61b5b88650b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=80"
          />
        </Grid>
      </section>
    </main>
  </>
);

export const getStaticProps: GetStaticProps = async () => {
  // Membaca isi direktori posts
  const filename: string[] = fs.readdirSync("posts");
  console.log(filename);
};

export default Index;

----

. Jalankan _development server_ dan periksa tampilan _terminal_ atau _command prompt_. Maka akan muncul daftar isi _file_ pada direktori *posts*

Kita sudah dapat daftar _file_ dalam direktori *posts*, selanjutnya kita perlu mengimpor metadata dari setiap _file_. Pasti kita akan melakukannya seperti ini

[source,ts]
----
export const getStaticProps: GetStaticProps = async () => {
  // Membaca isi direktori
  const filename: string[] = fs.readdirSync("posts");
  // Menyimpan metadata tiap file
  let posts: object[] = [];

  for (let i = 0; i < filename.length; i++) {
    let obj = import {meta} from `posts/${filename[i]}`
    // Mem-passing metadata file ke array
    posts.push(obj);
  }
}

----

Sayangnya itu tidak bisa dilakukan dan akan muncul _error_ seperti ini

[source,console]
----
An import declaration can only be used in a namespace or module.

----

Lalu bagaimana caranya untuk melakukan `import` secara dinamis? Fitur _https://v8.dev/features/dynamic-import[dynamic import]_ ini membantu kita untuk mengatasi masalah ini. Kita akan mengubah kode kita sebelumnya menjadi seperti ini

[source,ts]
----
// let obj = import {meta} from `posts/${filename[i]}`
let obj = await import(`posts/${filename[i]}`).then((mod) => mod.meta);

----

sekarang tinggal mem-_passing_-nya pada `props` dengan mengubah isi fungsinya menjadi seperti ini

[source,ts]
----
export const getStaticProps: GetStaticProps = async () => {
  // Membaca isi direktori
  const filename: string[] = fs.readdirSync("posts");
  // Menyimpan metadata tiap file
  let posts: object[] = [];

  for (let i = 0; i < filename.length; i++) {
    // let obj = import {meta} from `posts/${filename[i]}`
    let obj = await import(`posts/${filename[i]}`).then((mod) => mod.meta);
    // Mem-passing metadata file ke array
    posts.push(obj);
  }

  // Passing props
  return {
    props: {
      posts,
    },
  };
};

----

Kenapa kita perlu menambahkan `return` berupa _object_ ? Fungsi dari `getStaticProps` ini untuk mem-_passing_ data ke halaman saat proses _pre-rendering_ melalui _props_. Ibaratnya kalau kita disuruh Ibu beli sayur ke pasar, ketika di rumah kita dikasih sejumlah uang dan catatan apa aja yang perlu dibeli. Nantinya ketika di pasar kita tinggal membeli sayur sesuai yang di catatan itu.

Ketika Ibu memberikan catatan disini sama dengan proses _pre-rendering_ dan catatan itu sendiri merupakan `return` _object_-nya. Pada saat kita membeli sayur, berarti disini sama seperti ketika terjadi proses _client-side rendering_ yang mana mendapatkan data dari `props` atau ibarat catatan mengenai apa aja yang diperlukan. Sehingga nantinya tampilan yang didapatkan sesuai dengan _props_ itu atau sayur yang dibeli sesuai dengan catatan Ibu.

_Kembaliannya bisa buat beli kuo– eh permen_

Setelah membuat fungsi tersebut kita tinggal menggunakannya pada _Functional Component_ dengan menambahkan nama _props_ sesuai dengan yang di `return` pada fungsi `getStaticProps`

[source,tsx]
----
const Index: React.FC = ({ posts }) => {};

----

Kita sudah bisa mendapatkan data dari _file_ `.mdx` secara dinamis dan tinggal menampilkannya pada _Functional Component_ seperti ini

[source,tsx]
----
const Index: React.FC<indexProps> = ({ posts }: indexProps) => {
  return (
    <>
      <Navbar logo="http://www.coolgenerator.com/Data/Textdesign/202008/535249cb9a77839f16f715f25637ec7e.png" />
      <main>
        <section id="featured-post">
          <Featured
            title={posts[0].title}
            description={posts[0].description}
            cover={posts[0].cover}
            path={`blog/${posts[0].uid}`}
          />
        </section>
        <section id="latest-post">
          <Grid col="320px 320px 320px" row="auto" gap="30px" justify="center">
            {posts.map((v, i) => {
              if (i > 0)
                return (
                  <Link href="blog/[uid]" as={`blog/${v.uid}`}>
                    <a style={{ color: "black", textDecoration: "none" }}>
                      <Card
                        title={v.title}
                        subtitle={v.description}
                        cover={v.cover}
                      />
                    </a>
                  </Link>
                );
            })}
          </Grid>
        </section>
      </main>
      <Footer />
    </>
  );
};

----

_Pastikan semua file `.mdx` terdapat objek bernama `meta`_

Kita sudah bisa menampilkan daftar _post_ secara dinamis, namun masih ada 1 masalah lagi. Apabila kita membuka _file_ *[uid].mdx*, kita belum mendesain kontennya. Mari kita ubah terlebih dahulu:

[source,tsx]
----
import * as React from "react";
import { MDXProvider } from "@mdx-js/react";
import Content from "posts/post-1.mdx";
import { Title, Subtitle, Paragraph, Image, Navbar, Footer } from "@/.";

// Markdown custom component
const components: object = {
  h1: Title,
  h2: Subtitle,
  p: Paragraph,
  img: Image,
};

const Blog = () => {
  return (
    <>
      <Navbar logo="http://www.coolgenerator.com/Data/Textdesign/202008/535249cb9a77839f16f715f25637ec7e.png" />
      <main style={{ fontFamily: "sans-serif" }}>
        <MDXProvider components={components}>
          <Content />
        </MDXProvider>
      </main>
      <Footer />
    </>
  );
};

export default Blog;

----

Simpan perubahannya dan coba jalankan _development server_. Tampilannya akan sama seperti pada _post_ pertama kalinya.

Masalahnya belum selesai disini, kita ingin tampilannya supaya dinamis dan menyesuaikan konten yang telah dibuat. Meskipun URL-nya sudah dinamis, tapi percuma saja bila konten yang ditampilkan tetap sama. Disini kita akan mengatur supaya tampilan konten yang didapat sesuai dengan URL yang diberikan.

=== getStaticPaths

Apa yang akan kita lakukan disini adalah mengambil parameter dari URL untuk digunakan sebagai nama _file_ yang kita `import` di `getStaticProps`. Menurut https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation[dokumentasi] NextJS, `getStaticPaths` disini berfungsi memberitahu _server_ mengenai apa saja parameter URL yang digunakan untuk me-_render_ halaman. Jika sebelumnya bila kita mengakses `blog/[uid]` bisa diubah menjadi `blog/post-1` maupun `blog/my-post` dan menghasilkan tampilan yang sama. Apabila menggunakan `getStaticPaths` nantinya hanya halaman URL tertentu yang memiliki tampilan, sisanya akan diarahkan ke halaman 404 _(Not Found)_.

Sebelum membuat fungsi `getStaticPaths` kita *wajib* membuat fungsi `getStaticProps` terlebih dahulu. Maka kita buat fungsi `getStaticProps` seperti berikut:

. Tambahkan `import` pada _file_ *[uid].tsx* pada _folder_ *blog* seperti berikut:
[source,tsx]
----
import { GetStaticProps, GetStaticPaths } from "next";
import fs from "fs";

----

. Tambahkan fungsi `getStaticProps`
[source,tsx]
----
export const getStaticProps: GetStaticProps = async () => {};

----

. Tambahkan fungsi `getStaticPaths`
[source,tsx]
----
export const getStaticPaths: GetStaticPaths = async () => {
  // Membaca direktori
  const filenames: string[] = fs.readdirSync("posts");
  // Membuat array berisi object parameter
  const paths = filenames.map((file) => {
    return {
      params: {
        uid: file.replace(".mdx", ""),
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

----

Dalam fungsi `getStaticPaths` kita membaca isi direktori *posts* yang kemudian disimpan dalam sebuah variabel berupa _array_. Kemudian kita melakukan _mapping_ dengan cara seperti ini

[source,ts]
----
const paths = filenames.map((file) => {
  return {
    params: {
      uid: file.replace(".mdx", ""),
    },
  };
});

----

Dimana nanti isi variabel `paths` menjadi

[source,js]
----
paths = [
  { params: { uid: "post-1" } },
  { params: { uid: "post-2" } },
  { params: { uid: "post-3" } },
  { params: { uid: "post-4" } },
];

----

`uid` disini mengikuti nama _file_ yang sebelumnya kita buat, yaitu *[uid].tsx*. Apabila kita menamai _file_-nya dengan *[slug].tsx* maka nanti kita mengubah `uid` menjadi `slug` sebagai _value_ dari `params` sehingga jadinya `{params : {slug: &quot;post-1&quot; }}`

Pada baris terakhir dari _file_ tersebut kita juga memberi `return` yang berisi

[source,js]
----
return {
  paths,
  fallback: false,
};

----

`paths` disini merupakan variabel array yang sebelumnya sudah kita bahas, `fallback` disini berfungsi untuk memberitahu pada _server_ apa yang dilakukan apabila kita mengakses URL yang tidak memiliki halaman, misalnya `http://localhost:3000/blog/post-2xx`. Bila kita mengaturnya `false` maka ketika mengakses URL tersebut akan menampilkan halaman 404 _(Not Found)_, sedangkan bila kita atur `true` maka kita harus meng-_handle_-nya secara manual apabila terdapat URL yang tidak ada halamannya. Penjelasan lebih lengkapnya ada https://nextjs.org/docs/basic-features/data-fetching#the-fallback-key-required[disini].

Sekarang kita telah memberitahu _server_ parameter URL apa saja yang memiliki konten. Namun, bagaimana caranya agar ketika mengakses `blog/post-1` maka akan menampilkan isi _file_ *post-1.mdx* ?

Kita bisa melakukannya di `getStaticProps` dengan memodifikasinya seperti ini

[source,tsx]
----
export const getStaticProps: GetStaticProps = async ({ params }) => {
  const filename = `posts/${params.uid}.mdx`;
  return {
    props: {
      filename,
    },
  };
};

----

Bila kita perhatikan, disitu terdapat _props_ bernama `params`. Kita bisa mendapatkan parameter URL dari itu, jadi ketika mengakses `blog/post-1` maka isi `params.uid` adalah `post-1`. Disini kita tinggal menggabungkannya dengan lokasi _file_ dari konten kita kemudian me-`return`-nya untuk ditampilkan pada _Functional Component_

Disini kita tidak melakukan _dynamic import_ di `getStaticProps` namun akan langsung melakukannya di _Functional Component_. Ini karena fungsi `getStaticProps` berjalan di _server_ dan di _server_ belum terjadi _rendering_ sehingga apabila kita meng-_import_ komponen akan mendapat hasil yang tidak sesuai ekspektasi.

Lalu bagaimana?

Disini kita akan menggunakan fitur lain dari NextJS untuk melakukan _https://nextjs.org/docs/advanced-features/dynamic-import[dynamic import]_

. Tambahkan `import` pada _file_ *[uid].tsx*
[source,tsx]
----
import dynamic from "next/dynamic";

----

. Selanjutnya ubahlah _Functional Component_ menjadi seperti berikut
[source,tsx]
----
const Blog = ({ filename }: indexProps) => {
  // Dynamic import
  const Content = dynamic(() => import(`../../${filename}`));
  return (
    <>
      <Navbar logo="http://www.coolgenerator.com/Data/Textdesign/202008/535249cb9a77839f16f715f25637ec7e.png" />
      <main style={{ fontFamily: "sans-serif" }}>
        <MDXProvider components={components}>
          <Content />
        </MDXProvider>
      </main>
      <Footer />
    </>
  );
};

----

. Jalankan _development server_ kemudian coba lakukan navigasi dari halaman utama.

. Coba ubahlah parameternya menjadi `blog/post-2xx`, tampilannya nanti adalah halaman 404

Bila kita perhatikan pada variabel `Content`

[source,js]
----
const Content = dynamic(() => import(`../../${filename}`));
----

Disini kita melakukan `import` seperti biasa namun dengan tambahan fungsi `dynamic()` untuk mengimpor komponen. Fitur ini sama dengan _dynamic import_ sebelumnya namun bedanya disini kita bisa mengimpor _React Component_ secara dinamis sehingga kita bisa menggunakannya di dalam _Functional Component_ yang sudah kita buat.

== Selesai!

== Yeay!!

Memang kita tidak fokus membuat blog yang _overkill_ agar alur pembuatannya mudah dipahami. Masih banyak yang perlu improvisasi dan tugas kita adalah mengeksplorasi segala cara yang bisa digunakan agar blog yang kita buat bisa berfungsi dengan baik.

____

I believe you have to be willing to be misunderstood if you're going to innovate.

&mdash; Jeff Bezos

____

'''

Sebenarnya ada lagi cara yang lebih mudah untuk membuat blog menggunakan MDX. Dimana kita tidak perlu melakukan konfigurasi manual seperti membaca direktori _file_, mengurutkan _file_ berdasarkan waktu pembuatannya, mendeteksi _tag_ dan sebagainya. Semua ini bisa kita lakukan dengan memanfaatkan CMS yang ada di internet kemudian mengonversi kontennya menggunakan MDX. Hal ini bisa kita lakukan menggunakan https://yarnpkg.com/package/next-mdx-remote[Next-MDX-Remote]

_Apakah perlu kita coba sama sama?_
