= Membuat Blog Menggunakan NextJS dan MDX [1-Pengenalan]
:author: Excel
:create_date: 2022-11-27T21:24:13
:tagline: Bikin Blog Hanya Menggunakan Markdown
:description: Bagaimana jika kita bisa membuat sebuah blog hanya menggunakan Markdown?
:tag: tutorial,js,indonesia

image::https://lh3.googleusercontent.com/pw/ACtC-3eovp4Ca6hOlkfduL82tUQmgrEHpVG80Ydl-RPWVEZNyTN2k8TtAXBOZoqLWqeayfLXaeURd9k3r_oVqOakzw9weIJihOB4KIfnsdZaUZJAeZiU5FcG5SENmtPPYtR3YngjkRPU0xIIag_etiVLMZIA=w1055-h659-no[Cover image]

_Markdown_ merupakan format tulisan dengan syntax sederhana yang ditujukan untuk memermudah membuat tulisan di web.
Dari yang sebelumnya menggunakan tanda `&lt; &gt;` layaknya HTML, diganti dengan simbol sederhana seperti tanda `\*`.
_Markdown_ sendiri sudah banyak diaplikasikan seperti di Github, Whatsapp, Discord dll. dengan sintaks yang bervariasi.
Misal ketika ingin membuat huruf tebal biasanya kita harus mengetik `&lt;strong&gt;Ini huruf tebal&lt;/strong&gt;` namun dengan _Markdown_ hanya dengan mengetik `*Ini huruf tebal*` dengan hasil yang sama yaitu *Ini huruf tebal*.

Bagaimana jika kita bisa membuat sebuah blog hanya menggunakan _Markdown_?
https://twitter.com/rauchg[Guillermo Rauch] yang merupakan CEO https://twitter.com/rauchg[Vercel]
(sebelumnya Zeit dan juga Now) membuat https://spectrum.chat/thread/1021be59-2738-4511-aceb-c66921050b9a[proposal]
yang mengintegrasikan _Markdown_ dengan _React Component_ yang disebutnya dengan https://mdxjs.com/[MDX].

Kita akan mencoba membuat blog sederhana menggunakan MDX dan
https://nextjs.org/[NextJS] untuk mengetahui seberapa mudah membuat blog hanya dengan menggunakan _Markdown_

== Preparasi

Sebelum mulai membuat, kita perlu menyiapkan beberapa hal untuk memudahkan proses pengerjaan kita nanti.

=== Persyaratan

* https://nodejs.org/[NodeJS 12+]
* NPM 6+ atau https://classic.yarnpkg.com/en/docs/install[Yarn 1.20+]
* _Text Editor_ (JetBrains, Sublime Text, Visual Studio Code, dll.)
* Koneksi Internet

Pastikan persyaratan di atas telah terpenuhi untuk bisa mengikuti langkah berikutnya.

=== Struktur Folder

Dalam membuat projek, kita perlu memerhatikan struktur _folder_ yang dibuat agar memudahkan dalam mengatur perubahan _file_ dan terlihat rapi.

. Buatlah _folder_ baru bernama *Next MDX Blog*
. Buka _folder_ tersebut dan buat beberapa _folder_ baru di dalamnya dengan nama berikut:
** components
** pages
** post

Kita akan tahu fungsi dari masing masing _folder_ tersebut ketika mengikuti langkah langkah berikutnya.

_Struktur yang ada pada contoh ini tidak bersifat mutlak, namun ditujukan untuk memudahkan me-maintain projek yang telah dibuat._

=== Package.json

Setiap kali membuat projek menggunakan NodeJS kita perlu membuat `package.json` untuk memberikan metadata informasi mengenai projek yang kita buat.

Buatlah _file_ bernama *package.json* di dalam _folder_ *Next MDX Blog*.
Kemudian bukalah _file_ tersebut dan ketik seperti berikut:

[source,json]
----
{
    "name" : "next_mdx_blog",
    "version" : "0.1.0",
    "private" : true
}

----

Simpanlah perubahan pada _file_ tersebut.

=== Instalasi Package

Ibarat sebuah masakan, kita perlu bumbu agar masakan kita siap saji.
Pada projek ini, kita butuh _package_ agar projek kita siap produksi.
Ketik perintah berikut pada _terminal_ atau _command prompt_ untuk meng-_install package_

[source,bash]
----
# Apabila menggunakan NPM
npm i next react react-dom @next/mdx @mdx-js/loader @mdx-js/react
npm i -D typescript @types/node @types/react

# Apabila menggunakan Yarn
yarn add next react react-dom @next/mdx @mdx-js/loader @mdx-js/react
yarn add -D typescript @types/node @types/react

----

Apabila kita buka _file_ *package.json* maka isinya akan berubah seperti berikut:

[source,json]
----
{
    "name": "next_mdx_blog",
    "version": "0.1.0",
    "private": true,
    "dependencies": {
        "@mdx-js/loader": "^1.6.16",
        "@mdx-js/react": "^1.6.16",
        "@next/mdx": "^9.5.2",
        "next": "^9.5.2",
        "react": "^16.13.1",
        "react-dom": "^16.13.1"
    },
    "devDependencies": {
        "@types/node": "^14.0.27",
        "@types/react": "^16.9.46",
        "typescript": "^3.9.7"
    }
}

----

_Versi dari _package_ di atas bisa jadi berbeda karena versi di atas merupakan versi terbaru saat tulisan ini dibuat.
Apabila terjadi kegagalan, pastikan untuk membaca dokumentasi dari _package_ tersebut terlebih dahulu._

=== Typescript

Apabila kita perhatikan pada _file_ *package.json*, disitu terdapat _package_ bernama _Typescript_. _Typescript_ disini akan membantu kita untuk meminimalisir terjadinya kesalahan penulisan pada kode _Javascript_ yang kita buat.

*_Belum belajar Typescript?
No problem!_*

Semua kode _Javascript_ dapat dijalankan di _Typescript_ sehingga tidak perlu khawatir bila belum pernah mencoba _typescript_. *Jangan pesimis dulu*, disini akan dijelaskan sekilas tentang fitur _typescript_ yang akan digunakan.

____

Perusahaan seperti Google, Airbnb, dan Slack juga telah https://www.typescriptlang.org/[menggunakan Typescript]!

____

*Bagaimana memulainya?*

. Buatlah _file_ *tsconfig.json* di dalam _folder_ *Next MDX Blog*

selesai.

Sementara ini kita kosongkan dulu _file_ tersebut dan lanjut ke langkah berikutnya.

=== Next.config.js

Apabila kita ingin menggunakan MDX pada NextJS, kita perlu menambah konfigurasi seperti yang disebutkan pada https://mdxjs.com/getting-started/next[dokumentasi MDX].

. Buatlah _file_ *next.config.js* pada _folder_ *Next MDX Blog*
. Salin kode berikut

[source,js]
----
const withMDX = require("@next/mdx")({
  extension: /\.mdx?$/,
});

module.exports = withMDX({
  pageExtensions: ["js", "jsx", "ts", "tsx", "md", "mdx"],
});
----

Konfigurasi tersebut akan mem-_parsing_ isi _file_ dengan format `.md` maupun `.mdx` menjadi _react component_

== Eksekusi

=== Hello World

Seperti biasa, kita perlu membuat _file_ uji coba untuk memastikan konfigurasi kita berhasil.

. Buat _file_ *hello.mdx* pada _folder_ *post*

. Isilah _file_ tersebut dengan teks berikut:

[source,md]
----
# Next MDX Blog

## MDX is [Awesome](https://mdxjs.com/)!

Hello World! This is my first MDX blog content
----

. Buat _file_ *index.tsx* pada _folder_ *pages*

. Isilah _file_ tersebut seperti berikut:

[source,tsx]
----
// Menggunakan module ReactJS
import * as React from "react";
// Mengimpor konten file hello.mdx
// Disini akan muncul error yang akan kita perbaiki di langkah berikutnya
import Hello from "../post/hello.mdx";

// Function Component
const Index: React.FC = () => (
    <div style={{textAlign:"center"}}>
        {/* Konten file MDX */}
        <Hello/>
    </div>
)

export default Index;
----

.

Apabila menggunakan _editor_ Visual Studio Code maka akan muncul *_1 error_* seperti berikut:

[source,console]
----
Cannot find module '../post/hello.mdx' or its corresponding type declarations.
----

. Abaikan sementara _error_ yang muncul, akan kita perbaiki nanti.

=== Run Development Server

Sekarang kita mulai lakukan uji coba apakah semua konfigurasi sudah sesuai, ikuti langkah berikut:

. Tambahkan _object_ berikut pada *package.json*

[source,json]
----
{
    "scripts": {
        "dev": "next",
        "build": "next build",
        "start": "next start"
    }
}
----

Sehingga isi *package.json* menjadi seperti berikut:

[source,json]
----
{
    "name": "next_mdx_blog",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "dev": "next",
        "build": "next build",
        "start": "next start"
    },
    "dependencies": {
        "@mdx-js/loader": "^1.6.16",
        "@mdx-js/react": "^1.6.16",
        "@next/mdx": "^9.5.2",
        "next": "^9.5.2",
        "react": "^16.13.1",
        "react-dom": "^16.13.1"
    },
    "devDependencies": {
        "@types/node": "^14.0.27",
        "@types/react": "^16.9.46",
        "typescript": "^3.9.7"
    }
}
----

. Jalankan perintah berikut pada _terminal_ atau _command prompt_

[source,bash]
----
# Apabila menggunakan NPM
npm run dev

# Apabila menggunakan yarn  
yarn dev
----

. Maka tampilannya akan muncul seperti berikut:

== Yay! Berhasil!!

Kita telah berhasil membuat konten blog sederhana menggunakan MDX.
Namun, tadi masih ada langkah yang kita lewati.

Sebelumnya, kita mendapatkan _error_ pada *index.tsx* namun _website_ kita tetap bisa berjalan secara normal.
Disinilah peran _Typescript_ untuk memberitahu kita mengenai kesalahan penulisan pada kode kita.

Untuk mengatasi _error_ tersebut sudah dijelaskan pada https://mdxjs.com/advanced/typescript[dokumentasi MDX] seperti berikut:

. Buat _file_ *mdx.d.ts* pada _folder_ *Next MDX Blog*
. Isi _file_ tersebut dengan kode berikut:

[source,ts]
----
declare module "*.mdx" {
  let MDXComponent: (props: any) => JSX.Element;
  export default MDXComponent;
}
----

. Simpan lalu buka kembali _file_ *index.tsx*.
Maka _error_ tersebut akan hilang.

Maksud dari isi _file_ *mdx.d.ts* yaitu memberitahu bahwa _file_ dengan _format_ `.mdx` merupakan _JSX element_ yang dikenali oleh ReactJS.
Memang apabila terbiasa dengan _Javascript_ akan cukup frustasi menggunakan _Typescript_, namun keunggulan dari _Typescript_ disini adalah ketika kita berkolaborasi dengan tim serta https://medium.com/codewey/mengapa-typescript-9914c7c14793[memermudah _debugging_] karena kita tahu letak kesalahan program kita yang belum tentu mudah ditemukan pada _Javascript_.

____

Kita dapat menyimpan file Markdown dengan format .md maupun .mdx

____

Pada _file_ *index.tsx* kita juga melihat "keanehan" lain ketika membuat _Function Component_.
Dimana biasanya kita membuat _Function Component_ seperti berikut

[source,jsx]
----
import * as React from "react";
const Index = () => (<h1> Hello </h1>)
----

Namun pada _file_ tersebut kita membuatnya seperti berikut

[source,tsx]
----
import * as React from "react";
const Index: React.FC = () => (<h1> Hello </h1>)
----

Pada saat membuat _Function Component_, kita memberitahu _Typescript_ bahwa fungsi yang kita buat adalah _Function Component_ sehingga isi dari fungsi tersebut akan menyesuaikan sintaks _Function Component_ dari ReactJS.
Bila kita ubah menjadi seperti berikut malah akan terdapat _error_

[source,tsx]
----
import * as React from "react";
const Index: React.FC = () => { // Error
   console.log("yellow")
   return 1
}
----

Bila ingin memperjelas lagi bahwa _Function Component_ harus mengembalikan _JSX Element_ maka kita bisa modifikasi fungsi kita menjadi seperti berikut

[source,tsx]
----
import * as React from "react";
const Index: React.FC = () :JSX.Element => (<h1> Hello </h1>)
----

Jika ingin belajar lebih jauh tentang _typescript_ bisa ikuti tutorial https://www.youtube.com/watch?v=CJ4cWe-jXBg&list=PLnQvfeVegcJbjCnML6FdusK-rl-oDRMXJ[disini] atau https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html[baca disini]

== Bonus!

*_Let me show you something_*

Sebelumnya, bila kita hendak meng-_import file_ kita harus mengetik `../post/hello.mdx`, bagaimana bila _file_ tersebut berada di _kedalaman 10 folder_ ?
Maka kita akan mengetik `../../../../../../../../../../post/hello.mdx`

Repot kan?
Disini kita akan menambahkan sedikit konfigurasi untuk memermudah hal tersebut.

Tadi kita sempat membuat _file_ *tsconfig.json*, sekarang coba buka kembali _file_ tersebut dan akan muncul konten seperti berikut:

[source,json]
----
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

----

Ya, kita memang tidak mengisi _file_ tersebut namun kita sudah terbantu oleh fitur dari NextJS sendiri seperti yang disebutkan di https://nextjs.org/docs/basic-features/typescript[dokumentasinya].
Kita juga bisa memodifikasi _file_ tersebut.

. Tambahkan 2 _properties_ berikut ini di baris setelah `&quot;compilerOptions&quot;`:
** `baseUrl` menentukan direktori utama
** `paths` membuat alias dari nama direktori

[source,json]
----
{
    "baseUrl": ".",
    "paths": {
        "@/*": ["components/*"]
    }
}
----

. Maka isi *tsconfig.json* menjadi seperti berikut:

[source,json]
----
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
        "@/*": ["components/*"]
    },
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

----

. Simpan lalu coba ubah isi _file_ *index.tsx* pada bagian di bawah ini:

[source,tsx]
----
// import Hello from "../posts/hello.mdx";
import Hello from "posts/hello.mdx";
----

. Simpan perubahan tersebut dan jalankan kembali _development server_

[source,bash]
----
# Apabila menggunakan NPM
npm run dev

# Apabila menggunakan yarn  
yarn dev
----

Penjelasan mengenai perubahan yang kita lakukan bisa dilihat https://www.typescriptlang.org/tsconfig[disini].

*_Kita telah berhasil membuat blog sederhana menggunakan MDX, berikutnya kita akan belajar lebih lanjut menggunakan React Component untuk memodifikasi tampilan markdown dan bagaimana Typescript sangat membantu proses pengembangan blog kita_*
